/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package super_puissance4_lo_negro;

/**
 *
 * @author doria
 */
public class fenetredejeu extends javax.swing.JFrame {
    
    private Joueur[] listeJoueurs=new Joueur[2];// on créer les attributs demandés
    private Joueur joueurCourant;
    private PlateauDeJeu plateau;

    
    /**
     * Creates new form fenetredejeu
     */
    public fenetredejeu() {
        initComponents();
        panneau_infos_joueurs.setVisible(false);  //on cache le panneau_infos_joueurs
        
        panneau_infos_jeu.setVisible(false);      //idem pour le panneau_infos_jeu
        
        for(int i=5; i>=0; i--){
            for(int j=0;j<7; j++){
                Cellule_graphique cellGraph = new Cellule_graphique();
                panneau_grille.add(cellGraph);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_création_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nom_Joueur2 = new javax.swing.JTextField();
        Nom_Joueur1 = new javax.swing.JTextField();
        btn_part = new javax.swing.JButton();
        panneau_infos_joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_Jcourant = new javax.swing.JLabel();
        Message = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panneau_infos_jeu = new javax.swing.JPanel();
        lbl_J1_nom = new javax.swing.JLabel();
        lbl_J1_desint = new javax.swing.JLabel();
        lbl_J1_couleur = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_J2_desint1 = new javax.swing.JLabel();
        lbl_J2_couleur1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_J2_nom2 = new javax.swing.JLabel();
        btn_col_6 = new javax.swing.JButton();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 672, 576));

        panneau_création_partie.setBackground(new java.awt.Color(204, 255, 204));
        panneau_création_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom Joueur2:");
        panneau_création_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel2.setText("Nom Joueur1:");
        panneau_création_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));
        panneau_création_partie.add(Nom_Joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 38, 130, -1));

        Nom_Joueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nom_Joueur1ActionPerformed(evt);
            }
        });
        panneau_création_partie.add(Nom_Joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 8, 130, -1));

        btn_part.setText("Démarrer partie");
        btn_part.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_partActionPerformed(evt);
            }
        });
        panneau_création_partie.add(btn_part, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(panneau_création_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 290, 110));

        panneau_infos_joueurs.setBackground(new java.awt.Color(204, 255, 204));
        panneau_infos_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("infos jeu");
        panneau_infos_joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));

        jLabel7.setText("Joueur Courant :");
        panneau_infos_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        lbl_Jcourant.setText("NomJoueur ");
        panneau_infos_joueurs.add(lbl_Jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        Message.setViewportView(jTextArea1);

        panneau_infos_joueurs.add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 70));

        getContentPane().add(panneau_infos_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 290, 140));

        panneau_infos_jeu.setBackground(new java.awt.Color(204, 255, 204));
        panneau_infos_jeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_J1_nom.setText("NomJoueur 1 ");
        panneau_infos_jeu.add(lbl_J1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        lbl_J1_desint.setText("nbdesintJoueur1");
        panneau_infos_jeu.add(lbl_J1_desint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, -1));

        lbl_J1_couleur.setText("CouleurJoueur1");
        panneau_infos_jeu.add(lbl_J1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel8.setText("Couleur :");
        panneau_infos_jeu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel9.setText("désintegrateurs :");
        panneau_infos_jeu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, -1));
        panneau_infos_jeu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 290, 10));

        lbl_J2_desint1.setText("nbdesintJoueur2");
        panneau_infos_jeu.add(lbl_J2_desint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 120, -1));

        lbl_J2_couleur1.setText("CouleurJoueur2");
        panneau_infos_jeu.add(lbl_J2_couleur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel10.setText("Joueur 2 :");
        panneau_infos_jeu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel11.setText("Couleur :");
        panneau_infos_jeu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel12.setText("désintegrateurs :");
        panneau_infos_jeu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("infos joueur");
        panneau_infos_jeu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, -1));

        jLabel13.setText("Joueur 1 :");
        panneau_infos_jeu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        lbl_J2_nom2.setText("NomJoueur 2");
        panneau_infos_jeu.add(lbl_J2_nom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        getContentPane().add(panneau_infos_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 290, 230));

        btn_col_6.setText("7");
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 10, -1, -1));

        btn_col_0.setText("1");
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btn_col_1.setText("2");
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 10, -1, -1));

        btn_col_2.setText("3");
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 10, -1, -1));

        btn_col_3.setText("4");
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 10, -1, -1));

        btn_col_4.setText("5");
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, -1));

        btn_col_5.setText("6");
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        setBounds(0, 0, 1074, 644);
    }// </editor-fold>//GEN-END:initComponents

    private void Nom_Joueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nom_Joueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nom_Joueur1ActionPerformed

    private void btn_partActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_partActionPerformed
        // TODO add your handling code here:
        //c'est ici que l'on peut écrire le code lié au bouton 
        
        panneau_infos_joueurs.setVisible(true);  //on affiche le panneau_infos_joueurs si le joueur clique sur bouton
        
        panneau_infos_jeu.setVisible(true);      //idem pour le panneau_infos_jeu
        
    }//GEN-LAST:event_btn_partActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredejeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredejeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Message;
    private javax.swing.JTextField Nom_Joueur1;
    private javax.swing.JTextField Nom_Joueur2;
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_part;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_J1_couleur;
    private javax.swing.JLabel lbl_J1_desint;
    private javax.swing.JLabel lbl_J1_nom;
    private javax.swing.JLabel lbl_J2_couleur1;
    private javax.swing.JLabel lbl_J2_desint1;
    private javax.swing.JLabel lbl_J2_nom2;
    private javax.swing.JLabel lbl_Jcourant;
    private javax.swing.JPanel panneau_création_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infos_jeu;
    private javax.swing.JPanel panneau_infos_joueurs;
    // End of variables declaration//GEN-END:variables
}
